version: 2.1
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run:
          name: Test the contract
          command: |
            mkdir build
            cp -r /tmp/build/* build
            cp -r /tmp/lib/* lib
            nix-shell --command 'make test'
