version: 2.1
jobs:
  build:
    docker:
      - image: ethereum/solc:0.5.16
    steps:
      - checkout
      - run:
          name: Install build essentials
          command: |
            apk update
            apk add git make
      - run:
          name: Compile the contract
          command: |
            make
            git diff --color --exit-code
